version: '3.2'

# Définition des services docker
services:
    # Ces services comprennent un serveur todo, trois clients, et un superviseur qui observe les tâches
    c1:
      # CORRECTIF ON BUILD L'IMAGE
      build:
        context: .
        dockerfile: Dockerfile.client

      # Premier client - Ajoute et retire des tâches automatiquement
      container_name: arret04-c1
      image: arret04-client-1
      tty: true

      # CORRECTIF Connection au Network:
      networks:
        - arret04-todo-net

      # CORRECTIF Variables globales nécessaires
      environment:
        - MONSERVEUR='s1'
        - MONNOM='c1'

    c2:
      # CORRECTIF ON BUILD L'IMAGE
      build:
        context: .
        dockerfile: Dockerfile.client

      # Premier client - Ajoute et retire des tâches automatiquement
      container_name: arret04-c2
      image: arret04-client-2
      tty: true

      # CORRECTIF Connection au Network:
      networks:
        - arret04-todo-net

      # CORRECTIF Variables globales nécessaires
      environment:
        - MONSERVEUR='s1'
        - MONNOM='c2'

    c3:
      # CORRECTIF ON BUILD L'IMAGE
      build:
        context: .
        dockerfile: Dockerfile.client

      # Premier client - Ajoute et retire des tâches automatiquement
      container_name: arret04-c3
      image: arret04-client-3
      tty: true
      
      # CORRECTIF Connection au Network:
      networks:
        - arret04-todo-net

      # CORRECTIF Variables globales nécessaires
      environment:
        - MONSERVEUR='s1'
        - MONNOM='c3'


    s1:
      # CORRECTIF ON BUILD L'IMAGE
      build:
        context: .
        dockerfile: Dockerfile.serveur

      # Serveur unique - Traite les demandes todo
      container_name: arret04-s1
      image: arret04-serveur
      tty: true
      volumes:
        - "./tmp_todo1:/todo"

      # CORRECTIF Connection au Network:
      networks:
        - arret04-todo-net

     
    gestionnaire:
      # CORRECTIF ON BUILD L'IMAGE
      build:
        context: .
        dockerfile: Dockerfile.gestionnaire

      # Permet d'observer les tâches en cours
      container_name: arret04-gestionnaire
      image: arret04-gestionnaire
      tty: true

      environment:
        - MONSERVEUR='s1'
        - MONNOM='g'

      # CORRECTIF Connection au Network:
      networks:
        - arret04-todo-net

# Réseau par défaut
networks:
  arret04-todo-net:
