apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: a5-client
  labels:
    app: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
        - name: a5-client
          image: a5-client:latest
          tty: true
          imagePullPolicy: Always
          env:
          - name: MONSERVEUR
            value: 's1' # Must match the service name in the server yaml
