apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: a6-client
  labels:
    app: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
        - name: c1
          image: a6-client
          tty: true
          imagePullPolicy: Never 
          env:
          - name: MONSERVEUR
            value: 's1' # Must match the service name in the server yaml