apiVersion: v1
kind: Service
metadata:
  name: db-connect
spec:
  selector:
    name: db-todo
  ports:
  - name: db-port
    protocol: TCP
    port: 5432
    targetPort: db-port
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: a5-db
  labels:
    app: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
        name: db-todo
    spec:
      containers:
        - name: db
          image: postgres:15
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
              name: db-port
          envFrom:
            - secretRef:
                name: db-secrets
          volumeMounts:
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
            - name: postgredb
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
        - name: mysql-initdb
          configMap:
            name: mysql-initdb-config
  
