version: '3.2'

# Définition des services docker
services:
    # Ces services comprennent trois serveurs todo, trois clients, et un superviseur qui observe les tâches
    c1:
      # CORRECTIF ON BUILD L'IMAGE
      build:
        context: .
        dockerfile: Dockerfile.client

      # Premier client - Ajoute et retire des tâches automatiquement
      container_name: arret03-c1
      image: arret03-client-1
      tty: true

      # CORRECTIF Connection au Network:
      networks:
        - arret03-todo-net

      # CORRECTIF Variables globales nécessaires
      environment:
        - MONSERVEUR='s1'
        - MONNOM='c1'


    c2:
      # CORRECTIF ON BUILD L'IMAGE
      build:
        context: .
        dockerfile: Dockerfile.client

      container_name: arret03-c2
      image: arret03-client-2
      tty: true

      # CORRECTIF Connection au Network:
      networks:
        - arret03-todo-net

      # CORRECTIF Variables globales nécessaires
      environment:
        - MONSERVEUR='s2'
        - MONNOM='c2'


    c3:
      # CORRECTIF ON BUILD L'IMAGE
      build:
        context: .
        dockerfile: Dockerfile.client

      container_name: arret03-c3
      image: arret03-client-3
      tty: true
      
      # CORRECTIF Connection au Network:
      networks:
        - arret03-todo-net

      # CORRECTIF Variables globales nécessaires
      environment:
        - MONSERVEUR='s3'
        - MONNOM='c3'


    s1:
      # CORRECTIF ON BUILD L'IMAGE
      build:
        context: .
        dockerfile: Dockerfile.serveur

      # Premier serveur - Traite les demandes todo
      container_name: arret03-s1
      image: arret03-serveur-1
      tty: true
      volumes:
        - "./tmp_todo1:/todo"

      # CORRECTIF Connection au Network:
      networks:
        - arret03-todo-net
      
    s2:
      # CORRECTIF ON BUILD L'IMAGE
      build:
        context: .
        dockerfile: Dockerfile.serveur

      container_name: arret03-s2
      image: arret03-serveur-2
      tty: true
      volumes:
        - "./tmp_todo2:/todo"

      # CORRECTIF Connection au Network:
      networks:
        - arret03-todo-net

    s3:
      # CORRECTIF ON BUILD L'IMAGE
      build:
        context: .
        dockerfile: Dockerfile.serveur

      container_name: arret03-s3
      image: arret03-serveur-3
      tty: true
      volumes:
        - "./tmp_todo3:/todo"

      # CORRECTIF Connection au Network:
      networks:
        - arret03-todo-net

    gestionnaire:
      # CORRECTIF ON BUILD L'IMAGE
      build:
        context: .
        dockerfile: Dockerfile.gestionnaire

      container_name: arret03-gestionnaire
      image: arret03-gestionnaire
      tty: true
      environment:
        - MONSERVEUR='s1,s2,s3'
        - MONNOM='c1,c2,c3'

      # CORRECTIF Connection au Network:
      networks:
        - arret03-todo-net

# Réseau par défaut
networks:
  arret03-todo-net:
