version: '3.2'

services:
  # Premier client - Ajoute et retire des tâches automatiquement

  c1:
    build: 
      context: .
      dockerfile: Dockerfile.client
    container_name: arret05-c1
    image: arret05-client
    depends_on:
      - s1
    tty: true
    networks:
      - arret05-todo-net
    environment:
      - MONSERVEUR='s1'
      - MONNOM='c1'

  # Deuxième client - Ajoute et retire des tâches automatiquement
  c2:
    build: 
      context: .
      dockerfile: Dockerfile.client
    container_name: arret05-c2
    image: arret05-client
    depends_on:
      - s1
    tty: true
    networks:
      - arret05-todo-net
    environment:
      - MONSERVEUR='s1'
      - MONNOM='c2'

  # Troisième client - Ajoute et retire des tâches automatiquement
  c3:
    build: 
      context: .
      dockerfile: Dockerfile.client
    container_name: arret05-c3
    image: arret05-client
    depends_on:
      - s1
    tty: true
    networks:
      - arret05-todo-net
    environment:
      - MONNOM='c3'
      - MONSERVEUR='s1'

  # Premier serveur - Traite les demandes todo
  s1:
    build: 
      context: .
      dockerfile: Dockerfile.serveur
    container_name: arret05-s1
    image: arret05-serveur
    tty: true
    depends_on:
    - db
    networks:
      - arret05-todo-net
    environment:
      - "DB_HOST=db"


  # Permet d'observer les tâches en cours
  gestionnaire:
      build: 
        context: .
        dockerfile: Dockerfile.gestionnaire
      container_name: arret05-gestionnaire
      image: arret05-gestionnaire
      tty: true
      networks:
        - arret05-todo-net
      depends_on:
        - s1
      environment:
        - MONSERVEUR='s1'
        - MONNOM='c1,c2,c3'

  # Permet d'enregistrer les tâches
  db:
    container_name: arret05-db
    image: postgres:15
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=postgres"
    networks:
      - arret05-todo-net
    volumes:
      - todo-db:/var/lib/postgresql/datum
      - ./init_db/sql:/docker-entrypoint-initdb.d/
    ports:
      - "8801:5432"

networks:
  arret05-todo-net:

volumes:
  todo-db:
