version: '3.2'

services:
  # Premier client - Ajoute et retire des tâches automatiquement
  c1:
    container_name: arret05-c1
    build: 
      dockerfile: Dockerfile.clients
    image: a5-client
    depends_on:
      - s5
    tty: true

  # Deuxième client - Ajoute et retire des tâches automatiquement
  c2:
    container_name: arret05-c2
    image: a5-client
    depends_on:
      - s5
    environment:
      - "MONSERVEUR=s10"
    tty: true

  # Troisième client - Ajoute et retire des tâches automatiquement
  c3:
    container_name: arret05-c3
    image: a5-client
    depends_on:
      - s5
    environment:
      - "MONNOM=c30"
    tty: true

  # Premier serveur - Traite les demandes todo
  s1:
    container_name: arret05-s1
    build: 
      dockerfile: Dockerfile.serveurs
    image: a5-serveur
    tty: true
    depends_on:
    - gestionnaire
    environment:
      - "DB_HOST=db_sergtsop"

  # Permet d'observer les tâches en cours
  gestionnaire:
      container_name: arret05-gestionnaire
      build: 
        dockerfile: Dockerfile.gestionnaire
      image: a5-gestionnaire
      tty: true
      environment:
        - MONSERVEUR='s1'
        - MONNOM='c1,c2,c3'

  # Permet d'enregistrer les tâches
  db:
    container_name: arret05-db
    image: postgres:15
    environment:
      - "POSTGRES_PASSWORD=sergtsop"
      - "POSTGRES_USER=sergtsop"
      - "POSTGRES_DB=sergtsop"
    volumes:
      - toodo-db:/var/lib/postgresql/datum
      - ./init_db/sql:/mauvais-docker-entrypoint-initdb.d/

volumes:
  todo-db: